// Copyright Robert Bosch GmbH, 2022. Part of the Eclipse Kuksa Project.
//
// All rights reserved. This configuration file is provided to you under the
// terms and conditions of the Eclipse Distribution License v1.0 which
// accompanies this distribution, and is available at
// http://www.eclipse.org/org/documents/edl-v10.php

// This is a base proto file for databroker and kuksa-val-basic
// function set

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: kuksa/val/v1/val.proto

package kuksa_grpc_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define which data we want
type EntryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string  `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	View   View    `protobuf:"varint,2,opt,name=view,proto3,enum=kuksa.val.v1.View" json:"view,omitempty"`
	Fields []Field `protobuf:"varint,3,rep,packed,name=fields,proto3,enum=kuksa.val.v1.Field" json:"fields,omitempty"`
}

func (x *EntryRequest) Reset() {
	*x = EntryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuksa_val_v1_val_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryRequest) ProtoMessage() {}

func (x *EntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuksa_val_v1_val_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryRequest.ProtoReflect.Descriptor instead.
func (*EntryRequest) Descriptor() ([]byte, []int) {
	return file_kuksa_val_v1_val_proto_rawDescGZIP(), []int{0}
}

func (x *EntryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *EntryRequest) GetView() View {
	if x != nil {
		return x.View
	}
	return View_VIEW_UNSPECIFIED
}

func (x *EntryRequest) GetFields() []Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Request a set of entries.
type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*EntryRequest `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuksa_val_v1_val_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuksa_val_v1_val_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_kuksa_val_v1_val_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetEntries() []*EntryRequest {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Global errors are specified in `error`.
// Errors for individual entries are specified in `errors`.
type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*DataEntry      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Errors  []*DataEntryError `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Error   *Error            `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuksa_val_v1_val_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kuksa_val_v1_val_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_kuksa_val_v1_val_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetEntries() []*DataEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetResponse) GetErrors() []*DataEntryError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *GetResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Define the data we want to set
type EntryUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry  *DataEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Fields []Field    `protobuf:"varint,2,rep,packed,name=fields,proto3,enum=kuksa.val.v1.Field" json:"fields,omitempty"`
}

func (x *EntryUpdate) Reset() {
	*x = EntryUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuksa_val_v1_val_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntryUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryUpdate) ProtoMessage() {}

func (x *EntryUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_kuksa_val_v1_val_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryUpdate.ProtoReflect.Descriptor instead.
func (*EntryUpdate) Descriptor() ([]byte, []int) {
	return file_kuksa_val_v1_val_proto_rawDescGZIP(), []int{3}
}

func (x *EntryUpdate) GetEntry() *DataEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *EntryUpdate) GetFields() []Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

// A list of entries to be updated
type SetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updates []*EntryUpdate `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuksa_val_v1_val_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuksa_val_v1_val_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_kuksa_val_v1_val_proto_rawDescGZIP(), []int{4}
}

func (x *SetRequest) GetUpdates() []*EntryUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

// Global errors are specified in `error`.
// Errors for individual entries are specified in `errors`.
type SetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error  *Error            `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Errors []*DataEntryError `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuksa_val_v1_val_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kuksa_val_v1_val_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_kuksa_val_v1_val_proto_rawDescGZIP(), []int{5}
}

func (x *SetResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *SetResponse) GetErrors() []*DataEntryError {
	if x != nil {
		return x.Errors
	}
	return nil
}

// Define what to subscribe to
type SubscribeEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string  `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	View   View    `protobuf:"varint,2,opt,name=view,proto3,enum=kuksa.val.v1.View" json:"view,omitempty"`
	Fields []Field `protobuf:"varint,3,rep,packed,name=fields,proto3,enum=kuksa.val.v1.Field" json:"fields,omitempty"`
}

func (x *SubscribeEntry) Reset() {
	*x = SubscribeEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuksa_val_v1_val_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEntry) ProtoMessage() {}

func (x *SubscribeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_kuksa_val_v1_val_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEntry.ProtoReflect.Descriptor instead.
func (*SubscribeEntry) Descriptor() ([]byte, []int) {
	return file_kuksa_val_v1_val_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SubscribeEntry) GetView() View {
	if x != nil {
		return x.View
	}
	return View_VIEW_UNSPECIFIED
}

func (x *SubscribeEntry) GetFields() []Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Subscribe to changes in datapoints.
type SubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*SubscribeEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuksa_val_v1_val_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuksa_val_v1_val_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_kuksa_val_v1_val_proto_rawDescGZIP(), []int{7}
}

func (x *SubscribeRequest) GetEntries() []*SubscribeEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// A subscription response
type SubscribeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updates []*EntryUpdate `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuksa_val_v1_val_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kuksa_val_v1_val_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_kuksa_val_v1_val_proto_rawDescGZIP(), []int{8}
}

func (x *SubscribeResponse) GetUpdates() []*EntryUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

type GetServerInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetServerInfoRequest) Reset() {
	*x = GetServerInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuksa_val_v1_val_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoRequest) ProtoMessage() {}

func (x *GetServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuksa_val_v1_val_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_kuksa_val_v1_val_proto_rawDescGZIP(), []int{9}
}

type GetServerInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *GetServerInfoResponse) Reset() {
	*x = GetServerInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuksa_val_v1_val_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoResponse) ProtoMessage() {}

func (x *GetServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kuksa_val_v1_val_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoResponse.ProtoReflect.Descriptor instead.
func (*GetServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_kuksa_val_v1_val_proto_rawDescGZIP(), []int{10}
}

func (x *GetServerInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetServerInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_kuksa_val_v1_val_proto protoreflect.FileDescriptor

var file_kuksa_val_v1_val_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6b, 0x75, 0x6b, 0x73, 0x61, 0x2f, 0x76, 0x61, 0x6c, 0x2f, 0x76, 0x31, 0x2f, 0x76,
	0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6b, 0x75, 0x6b, 0x73, 0x61, 0x2e,
	0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x1a, 0x18, 0x6b, 0x75, 0x6b, 0x73, 0x61, 0x2f, 0x76, 0x61,
	0x6c, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x77, 0x0a, 0x0c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x12, 0x26, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6b, 0x75, 0x6b, 0x73, 0x61, 0x2e, 0x76, 0x61, 0x6c, 0x2e, 0x76,
	0x31, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x52, 0x04, 0x76, 0x69, 0x65, 0x77, 0x12, 0x2b, 0x0a, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6b,
	0x75, 0x6b, 0x73, 0x61, 0x2e, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x42, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6b, 0x75, 0x6b, 0x73, 0x61,
	0x2e, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0xa1, 0x01,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a,
	0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x6b, 0x75, 0x6b, 0x73, 0x61, 0x2e, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x12, 0x34, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x6b, 0x75, 0x6b, 0x73, 0x61, 0x2e, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x29, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6b, 0x75, 0x6b, 0x73, 0x61, 0x2e, 0x76, 0x61,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x69, 0x0a, 0x0b, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x2d, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x6b, 0x75, 0x6b, 0x73, 0x61, 0x2e, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x2b, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32,
	0x13, 0x2e, 0x6b, 0x75, 0x6b, 0x73, 0x61, 0x2e, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x41, 0x0a, 0x0a,
	0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x07, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6b, 0x75,
	0x6b, 0x73, 0x61, 0x2e, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x22,
	0x6e, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x6b, 0x75, 0x6b, 0x73, 0x61, 0x2e, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x34, 0x0a, 0x06, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6b, 0x75, 0x6b, 0x73,
	0x61, 0x2e, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22,
	0x79, 0x0a, 0x0e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x26, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6b, 0x75, 0x6b, 0x73, 0x61, 0x2e, 0x76, 0x61, 0x6c, 0x2e,
	0x76, 0x31, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x52, 0x04, 0x76, 0x69, 0x65, 0x77, 0x12, 0x2b, 0x0a,
	0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x13, 0x2e,
	0x6b, 0x75, 0x6b, 0x73, 0x61, 0x2e, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x4a, 0x0a, 0x10, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36,
	0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x6b, 0x75, 0x6b, 0x73, 0x61, 0x2e, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65,
	0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x48, 0x0a, 0x11, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6b,
	0x75, 0x6b, 0x73, 0x61, 0x2e, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73,
	0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x45, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x32,
	0xa7, 0x02, 0x0a, 0x03, 0x56, 0x41, 0x4c, 0x12, 0x3a, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x18,
	0x2e, 0x6b, 0x75, 0x6b, 0x73, 0x61, 0x2e, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6b, 0x75, 0x6b, 0x73, 0x61,
	0x2e, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x03, 0x53, 0x65, 0x74, 0x12, 0x18, 0x2e, 0x6b, 0x75, 0x6b,
	0x73, 0x61, 0x2e, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6b, 0x75, 0x6b, 0x73, 0x61, 0x2e, 0x76, 0x61, 0x6c,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4e, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x1e, 0x2e, 0x6b,
	0x75, 0x6b, 0x73, 0x61, 0x2e, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6b,
	0x75, 0x6b, 0x73, 0x61, 0x2e, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12,
	0x58, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x22, 0x2e, 0x6b, 0x75, 0x6b, 0x73, 0x61, 0x2e, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x6b, 0x75, 0x6b, 0x73, 0x61, 0x2e, 0x76, 0x61, 0x6c,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x2f, 0x6b, 0x75,
	0x6b, 0x73, 0x61, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kuksa_val_v1_val_proto_rawDescOnce sync.Once
	file_kuksa_val_v1_val_proto_rawDescData = file_kuksa_val_v1_val_proto_rawDesc
)

func file_kuksa_val_v1_val_proto_rawDescGZIP() []byte {
	file_kuksa_val_v1_val_proto_rawDescOnce.Do(func() {
		file_kuksa_val_v1_val_proto_rawDescData = protoimpl.X.CompressGZIP(file_kuksa_val_v1_val_proto_rawDescData)
	})
	return file_kuksa_val_v1_val_proto_rawDescData
}

var file_kuksa_val_v1_val_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_kuksa_val_v1_val_proto_goTypes = []interface{}{
	(*EntryRequest)(nil),          // 0: kuksa.val.v1.EntryRequest
	(*GetRequest)(nil),            // 1: kuksa.val.v1.GetRequest
	(*GetResponse)(nil),           // 2: kuksa.val.v1.GetResponse
	(*EntryUpdate)(nil),           // 3: kuksa.val.v1.EntryUpdate
	(*SetRequest)(nil),            // 4: kuksa.val.v1.SetRequest
	(*SetResponse)(nil),           // 5: kuksa.val.v1.SetResponse
	(*SubscribeEntry)(nil),        // 6: kuksa.val.v1.SubscribeEntry
	(*SubscribeRequest)(nil),      // 7: kuksa.val.v1.SubscribeRequest
	(*SubscribeResponse)(nil),     // 8: kuksa.val.v1.SubscribeResponse
	(*GetServerInfoRequest)(nil),  // 9: kuksa.val.v1.GetServerInfoRequest
	(*GetServerInfoResponse)(nil), // 10: kuksa.val.v1.GetServerInfoResponse
	(View)(0),                     // 11: kuksa.val.v1.View
	(Field)(0),                    // 12: kuksa.val.v1.Field
	(*DataEntry)(nil),             // 13: kuksa.val.v1.DataEntry
	(*DataEntryError)(nil),        // 14: kuksa.val.v1.DataEntryError
	(*Error)(nil),                 // 15: kuksa.val.v1.Error
}
var file_kuksa_val_v1_val_proto_depIdxs = []int32{
	11, // 0: kuksa.val.v1.EntryRequest.view:type_name -> kuksa.val.v1.View
	12, // 1: kuksa.val.v1.EntryRequest.fields:type_name -> kuksa.val.v1.Field
	0,  // 2: kuksa.val.v1.GetRequest.entries:type_name -> kuksa.val.v1.EntryRequest
	13, // 3: kuksa.val.v1.GetResponse.entries:type_name -> kuksa.val.v1.DataEntry
	14, // 4: kuksa.val.v1.GetResponse.errors:type_name -> kuksa.val.v1.DataEntryError
	15, // 5: kuksa.val.v1.GetResponse.error:type_name -> kuksa.val.v1.Error
	13, // 6: kuksa.val.v1.EntryUpdate.entry:type_name -> kuksa.val.v1.DataEntry
	12, // 7: kuksa.val.v1.EntryUpdate.fields:type_name -> kuksa.val.v1.Field
	3,  // 8: kuksa.val.v1.SetRequest.updates:type_name -> kuksa.val.v1.EntryUpdate
	15, // 9: kuksa.val.v1.SetResponse.error:type_name -> kuksa.val.v1.Error
	14, // 10: kuksa.val.v1.SetResponse.errors:type_name -> kuksa.val.v1.DataEntryError
	11, // 11: kuksa.val.v1.SubscribeEntry.view:type_name -> kuksa.val.v1.View
	12, // 12: kuksa.val.v1.SubscribeEntry.fields:type_name -> kuksa.val.v1.Field
	6,  // 13: kuksa.val.v1.SubscribeRequest.entries:type_name -> kuksa.val.v1.SubscribeEntry
	3,  // 14: kuksa.val.v1.SubscribeResponse.updates:type_name -> kuksa.val.v1.EntryUpdate
	1,  // 15: kuksa.val.v1.VAL.Get:input_type -> kuksa.val.v1.GetRequest
	4,  // 16: kuksa.val.v1.VAL.Set:input_type -> kuksa.val.v1.SetRequest
	7,  // 17: kuksa.val.v1.VAL.Subscribe:input_type -> kuksa.val.v1.SubscribeRequest
	9,  // 18: kuksa.val.v1.VAL.GetServerInfo:input_type -> kuksa.val.v1.GetServerInfoRequest
	2,  // 19: kuksa.val.v1.VAL.Get:output_type -> kuksa.val.v1.GetResponse
	5,  // 20: kuksa.val.v1.VAL.Set:output_type -> kuksa.val.v1.SetResponse
	8,  // 21: kuksa.val.v1.VAL.Subscribe:output_type -> kuksa.val.v1.SubscribeResponse
	10, // 22: kuksa.val.v1.VAL.GetServerInfo:output_type -> kuksa.val.v1.GetServerInfoResponse
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_kuksa_val_v1_val_proto_init() }
func file_kuksa_val_v1_val_proto_init() {
	if File_kuksa_val_v1_val_proto != nil {
		return
	}
	file_kuksa_val_v1_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_kuksa_val_v1_val_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuksa_val_v1_val_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuksa_val_v1_val_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuksa_val_v1_val_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntryUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuksa_val_v1_val_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuksa_val_v1_val_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuksa_val_v1_val_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuksa_val_v1_val_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuksa_val_v1_val_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuksa_val_v1_val_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServerInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuksa_val_v1_val_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServerInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kuksa_val_v1_val_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kuksa_val_v1_val_proto_goTypes,
		DependencyIndexes: file_kuksa_val_v1_val_proto_depIdxs,
		MessageInfos:      file_kuksa_val_v1_val_proto_msgTypes,
	}.Build()
	File_kuksa_val_v1_val_proto = out.File
	file_kuksa_val_v1_val_proto_rawDesc = nil
	file_kuksa_val_v1_val_proto_goTypes = nil
	file_kuksa_val_v1_val_proto_depIdxs = nil
}
